Rayos X/Versiones/solicitud_rayosx_15092019_serverversion/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/tramiteRayosX', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'RayosxController@index')->name('home');
Route::get('notes', 'NotesController@index');


Route::group(['middleware' => ['permission:destroy_notes']], function () {
    Route::get('notes/{id}/destroy', 'NotesController@destroy')->name('notes.destroy');
});

//Listado de tramites inicial
Route::any('/ventanilla/tramites', 'TramitesController@index')->middleware('auth')->name('tramites.index');

Route::any('/ventanilla/tramites/edit', 'TramitesController@edit')->middleware('auth')->name('tramites.edit');

//				--		SOLICITUD RAYOS X 				--

//Descripcion del tramite


Route::get('/ventanilla/tramites/solicitud_rayosx', 'RayosxController@index')->name('rayosx.index')->middleware('auth');

//Crear nuevo rayos x
Route::any('/ventanilla/tramites/solicitud_rayosx/crear', 'RayosxController@create')->name('rayosx.create')->middleware('auth');

Route::any('/tramites/creartramiterayosx', 'RayosxController@crearTramiteRayosx')->name('rayosx.crearTramiteRayosx')->middleware('auth');

Route::any('/tramites/guardartramiterayosx', 'RayosxController@guardarTramiteRayosx')->name('rayosx.guardarTramiteRayosx')->middleware('auth');

Route::post('/tramite/editardireccion/', 'RayosxController@editarDireccion')->name('rayosx.editarDireccion')->middleware('auth');

Route::post('/tramite/editarequipo/', 'RayosxController@editarEquipo')->name('rayosx.editarEquipo')->middleware('auth');

Route::post('/tramite/editaroficialtoe/', 'RayosxController@editarOficialToe')->name('rayosx.editarOficialToe')->middleware('auth');

Route::post('/tramite/editardirector/', 'RayosxController@editarDirector')->name('rayosx.editarDirector')->middleware('auth');

Route::post('/tramite/editardocumentos1/', 'RayosxController@editarDocumentos1')->name('rayosx.editarDocumentos1')->middleware('auth');

Route::post('/tramite/editardocumentos2/', 'RayosxController@editarDocumentos2')->name('rayosx.editarDocumentos2')->middleware('auth');

Route::post('/tramite/guardardocumentos1/', 'RayosxController@guardarDocumentos1')->name('rayosx.guardarDocumentos1')->middleware('auth');

Route::post('/tramite/guardardocumentos2/', 'RayosxController@guardarDocumentos2')->name('rayosx.guardarDocumentos2')->middleware('auth');
//Editar  rayos x
Route::any('/ventanilla/tramites/solicitud_rayosx/tramite/{idtramite}', 'RayosxController@edit')->middleware('auth');

Route::any('/ventanilla/tramites/solicitud_rayosx/resolucion1/{idtramite}', 'PdfController@resolucion1')->middleware('auth');

Route::any('/ventanilla/tramites/solicitud_rayosx/resolucion2/{idtramite}', 'PdfController@resolucion2')->middleware('auth');

Route::any('/ventanilla/tramites/solicitud_rayosx/resolucion3/{idtramite}', 'PdfController@resolucion3')->middleware('auth');

Route::any('/ventanilla/tramites/solicitud_rayosx/gestionarFlujo', 'RayosxController@gestionarFlujoTramiteRayosx')->name('rayosx.gestionarFlujoTramiteRayosx')->middleware('auth');

//Editar  rayos x equipo
Route::any('/ventanilla/tramites/solicitud_rayosx/tramite/editardireccion/', 'RayosxController@editardireccion')->name('rayosx.editardireccion')->middleware('auth');

//RAYOS X - Guardar localizacion entidad
Route::any('/tramites/guardarlocalizacion', 'RayosxController@guardarLocalizacion')->name('rayosx.guardarLocalizacion')->middleware('auth');

//RAYOS X - Guardar equipos de rayosX
Route::any('/ventanilla/tramites/solicitud_rayosx/formSeccion2', 'RayosxController@guardarEquiposRayosX')->name('rayosx.guardarEquiposRayosX')->middleware('auth');

//RAYOS X - Guardar oficial TOE
Route::any('/ventanilla/tramites/solicitud_rayosx/formSeccion3-1', 'RayosxController@guardarOficialTOE')->name('rayosx.guardarOficialTOE')->middleware('auth');

//RAYOS X - Guardar oficial TOE
Route::any('/ventanilla/tramites/solicitud_rayosx/formSeccion3-2', 'RayosxController@guardarTemporalTOE')->name('rayosx.guardarTemporalTOE')->middleware('auth');

//RAYOS X - VERIFICAR TOE y PASO 4S
Route::any('/ventanilla/tramites/solicitud_rayosx/formSeccion4', 'RayosxController@verificarTOE')->name('rayosx.verificarTOE')->middleware('auth');

//RAYOS X - Guardar oficial TOE
Route::any('/ventanilla/tramites/solicitud_rayosx/formSeccion4-1', 'RayosxController@guardarTalentoHumano')->name('rayosx.guardarTalentoHumano')->middleware('auth');

Route::any('/ventanilla/tramites/solicitud_rayosx/formSeccion4-2', 'RayosxController@guardarEquipoPrueba')->name('rayosx.guardarEquipoPrueba')->middleware('auth');

Route::any('/ventanilla/tramites/solicitud_rayosx/formSeccion5', 'RayosxController@verificarPaso4')->name('rayosx.verificarPaso4')->middleware('auth');

//guardar rayos x
Route::get('/ventanilla/tramites/solicitud_rayosx/store', 'RayosxController@store')->middleware('auth');


//consultar rayos x
//Avanzar tramite
//Devolver tramite

Route::get('/municipio/get/{id}', 'RayosxController@getMpoXDpto');
Route::get('/categoriaequipo/get/{id}', 'RayosxController@getEquipoXCategoria');
Route::get('(localidad/get/{id}', 'RayosxController@getLocalidadXMpo');
Route::get('/barrio/get/{id}', 'RayosxController@getBarrioXLocalidad');

//ADMINISTRADOR
//guardar rayos x
Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');
Route::resource('permissions', 'PermissionController');

Rayos X/Versiones/solicitud_rayosx_15092019_serverversion/app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    //
}

Rayos X/Versiones/solicitud_rayosx_15092019_serverversion/app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Session;

class PermissionController extends Controller
{
    public function __construct() 
    {
        $this->middleware(['auth', 'isAdmin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::all();

        return view('permissions.index')->with('permissions', $permissions);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::get();

        return view('permissions.create')->with('roles', $roles);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $this->validate($request, [
            'name'=>'required|max:40',
        ]);

        $name = $request['name'];
        $permission = new Permission();
        $permission->name = $name;

        $roles = $request['roles'];
        
        $permission->save();

        if (!empty($request['roles'])) {
            foreach ($roles as $role) {
                $r = Role::where('id', '=', $role)->firstOrFail(); //Match input role to db record

                $permission = Permission::where('name', '=', $name)->first();   
                $r->givePermissionTo($permission);
            }
        }

        return redirect()->route('permissions.index')
            ->with('flash_message',
             'Permission'. $permission->name.' added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect('permissions');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permission = Permission::find($id);
        
        return view('permissions.edit', compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $permission = Permission::findOrFail($id);

        $this->validate($request, [
            'name'=>'required|max:40',
        ]);
        
        $input = $request->all();
        $permission->fill($input)->save();

        return redirect()->route('permissions.index')
            ->with('flash_message',
             'Permission'. $permission->name.' updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $permission = Permission::findOrFail($id);
        
        if ($permission->name == "Administer roles & permissions") {
            return redirect()->route('permissions.index')
            ->with('flash_message',
             'Cannot delete this Permission!');
        }
        
        $permission->delete();

        return redirect()->route('permissions.index')
            ->with('flash_message',
             'Permission deleted!');
    }
}

Rayos X/Versiones/solicitud_rayosx_15092019_serverversion/resources/views/admin/permissions/create.blade.php
{{-- \resources\views\admin\permissions\create.blade.php --}}
@extends('layouts.layout')

@section('title', '| Create Permission')

@section('content')

<div class='col-lg-4 col-lg-offset-4'>

    <h1><i class='fa fa-key'></i> Add Permission</h1>
    <br>

    {{ Form::open(array('url' => 'permissions')) }}

    <div class="form-group">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', '', array('class' => 'form-control')) }}
    </div><br>
    @if(!$roles->isEmpty()) //If no roles exist yet
        <h4>Assign Permission to Roles</h4>

        @foreach ($roles as $role) 
            {{ Form::checkbox('roles[]',  $role->id ) }}
            {{ Form::label($role->name, ucfirst($role->name)) }}<br>

        @endforeach
    @endif
    <br>
    {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}

    {{ Form::close() }}

</div>

@endsection

Rayos X/Versiones/solicitud_rayosx_15092019_serverversion/resources/views/admin/permissions/edit.blade.php
@extends('layouts.layout')

@section('title', '| Edit Permission')

@section('content')

<div class='col-lg-4 col-lg-offset-4'>

    <h1><i class='fa fa-key'></i> Edit {{$permission->name}}</h1>
    <br>
    {{ Form::model($permission, array('route' => array('permissions.update', $permission->id), 'method' => 'PUT')) }}{{-- Form model binding to automatically populate our fields with permission data --}}

    <div class="form-group">
        {{ Form::label('name', 'Permission Name') }}
        {{ Form::text('name', null, array('class' => 'form-control')) }}
    </div>
    <br>
    {{ Form::submit('Edit', array('class' => 'btn btn-primary')) }}

    {{ Form::close() }}

</div>

@endsection

Rayos X/Versiones/solicitud_rayosx_15092019_serverversion/resources/views/admin/permissions/index.blade.php
{{-- \resources\views\admin\permissions\index.blade.php --}}
@extends('layouts.layout')

@section('title', '| Permissions')

@section('content')

<div class="col-lg-10 col-lg-offset-1">
    <h1><i class="fa fa-key"></i>Available Permissions

    <a href="{{ route('users.index') }}" class="btn btn-default pull-right">Users</a>
    <a href="{{ route('roles.index') }}" class="btn btn-default pull-right">Roles</a></h1>
    <hr>
    <div class="table-responsive">
        <table class="table table-bordered table-striped">

            <thead>
                <tr>
                    <th>Permissions</th>
                    <th>Operation</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($permissions as $permission)
                <tr>
                    <td>{{ $permission->name }}</td> 
                    <td>
                    <a href="{{ URL::to('permissions/'.$permission->id.'/edit') }}" class="btn btn-info pull-left" style="margin-right: 3px;">Edit</a>

                    {!! Form::open(['method' => 'DELETE', 'route' => ['permissions.destroy', $permission->id] ]) !!}
                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                    {!! Form::close() !!}

                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <a href="{{ URL::to('permissions/create') }}" class="btn btn-success">Add Permission</a>

</div>

@endsection